### PR TITLE
Discord.js v14

### PR DESCRIPTION
**Pull request by treeot**
Discord.js has been updated to v14 with a lot of different builders.

### CODE REVIEW

**Comment by Korabi-dev** [comment]
This is NOT a good PR/commit. Why the hell are you using messages? It's like if I started listening to music on radio. Also no need to move to v14 at all v13 works just fine

**Comment by treeot** [comment]
Messages are only used for eval. I don't think having eval as a slash command is a good idea.

**Comment by FarazPatankar** [comment]
Hey @treeot, I am closing this as we've restructured how we manage templates. Feel free to open an issue [here](https://github.com/railwayapp-templates/discordjs) to discuss these changes before your PR them in! :)

**Comment by ndneighbor** [comment]
@Korabi-dev - I have removed your comment as it violates our contributor guidelines. Being rude to other contributors doesn't foster trust between you and other members. 

> This is NOT a good PR/commit. Why the hell are you using messages? 

Instead, be specific about the content of the PR rather than attacking the character of the submitter. Any further comments like this will result in a ban from these repos and the platform.

**Comment by treeot** [comment]
@FarazPatankar Sounds good. I'll discuss the changes before I PR them in on the new repository.

**Pull request closed without merging**
