### PR TITLE
add svelte-kit-prisma

### PR DESCRIPTION
**Pull request by mavthedev**
there is expressjs prisma and nextjs prisma, why not sveltekit as well?

### CODE REVIEW

**Comment by maverick-dev-55** [comment]
Is this going to be merged?

**Comment by ndneighbor** [comment]
Gotta spend some time to test it with the new buildpacks, sorry for the wait.

**Comment by maverick-dev-55** [comment]
ok! make sure to add the svelte kit adapter I don't think I added it

**Comment by maverick-dev-55** [comment]
infact, im going to add one to both svelte-kit and svelte-kit-prisma

**Comment by maverick-dev-55** [comment]
> infact, im going to add one to both svelte-kit and svelte-kit-prisma
**doesnt add them to both**

**Comment by maverick-dev-55** [comment]
ok i added them, you can merge whenever

**Comment by FarazPatankar** [comment]
Hey @mavthedev, I am closing this as we've restructured how we manage templates. Feel free to open a new issue to submit a template using the new template system mentioned in the updated README.

**Pull request closed without merging**
